#ifndef POKELOOKUP_HPP
#define POKELOOKUP_HPP

#include <CTRPluginFramework.hpp>
#include "stdafx.hpp"
#include "Helpers.hpp"

namespace CTRPluginFramework {
    extern u16 spwnSpecies;
    extern u8 spawnLv, spwnForm;

    static StringVector ListOfForms(int pokeNo) {
        StringVector options;

        switch (pokeNo) {
            case 3:   // Venusaur
            case 9:   // Blastoise
            case 65:  // Alakazam
            case 94:  // Gengar
            case 115: // Kangaskhan
            case 127: // Pinsir
            case 130: // Gyarados
            case 142: // Aerodactyl
            case 181: // Ampharos
            case 208: // Steelix
            case 212: // Scizor
            case 214: // Heracross
            case 229: // Houndoom
            case 248: // Tyranitar
            case 257: // Blaziken
            case 282: // Gardevoir
            case 303: // Mawile
            case 306: // Aggron
            case 308: // Medicham
            case 310: // Manectric
            case 354: // Banette
            case 359: // Absol
            case 380: // Latias
            case 381: // Latios
            case 445: // Garchomp
            case 448: // Lucario
            case 460: // Abomasnow
                options = {"Normal", "Mega"};
                break;

            case 6:   // Charizard
            case 150: // Mewtwo
                options = {"Normal", "Mega X", "Mega Y"};
                break;

            case 201: // Unown
                options = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "!", "?"};
                break;

            case 351: // Castform
                options = {"Normal", "Sunny", "Rainy", "Snowy"};
                break;

            case 386: // Deoxys
                options = {"Normal", "Attack", "Defense", "Speed"};
                break;

            case 412: // Burmy
            case 413: // Wormadam
            case 414: // Mothim
                options = {"Plant", "Sandy", "Trash"};
                break;

            case 422: // Shellos
            case 423: // Gastrodon
                options = {"East", "West"};
                break;

            case 479: // Rotom
                options = {"Normal", "Heat", "Wash", "Frost", "Fan", "Mow"};
                break;

            case 487: // Giratina
                options = {"Altered", "Origin"};
                break;

            case 492: // Shaymin
                options = {"Land", "Sky"};
                break;

            case 493: // Arceus
                options = {"Normal", "Fighting", "Flying", "Poison", "Ground", "Rock", "Bug", "Ghost", "Steel", "Fire", "Water", "Grass", "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"};
                break;

            case 550: // Basculin
                options = {"Red", "Blue"};
                break;

            case 555: // Darmanitan
                options = {"Standard", "Zen"};
                break;

            case 585: // Deerling
            case 586: // Sawsbuck
                options = {"Spring", "Summer", "Autumn", "Winter"};
                break;

            case 641: // Tornadus
            case 642: // Thundurus
            case 645: // Landorus
                options = {"Incarnate", "Therian"};
                break;

            case 646: // Kyurem
                options = {"Normal", "White", "Black"};
                break;

            case 647: // Keldeo
                options = {"Ordinary", "Resolute"};
                break;

            case 648: // Meloetta
                options = {"Aria", "Pirouette"};
                break;

            case 649: // Genesect
                options = {"Normal", "Douse", "Shock", "Burn", "Chill"};
                break;

            case 664: // Scatterbug
            case 665: // Spewpa
            case 666: // Vivillon
                options = {"Icy Snow", "Polar", "Tundra", "Continental", "Garden", "Elegant", "Meadow", "Modern", "Marine", "Archipelago", "High-Plains", "Sandstorm", "River", "Monsoon", "Savannah", "Sun", "Ocean", "Jungle", "Fancy", "Poke Ball"};
                break;

            case 669: // Flabébé
            case 671: // Florges
                options = {"Red", "Yellow", "Orange", "Blue", "White"};
                break;

            case 670: // Floette
                options = {"Red", "Yellow", "Orange", "Blue", "White", "Eternal"};
                break;

            case 676: // Furfrou
                options = {"Natural", "Heart", "Star", "Diamond", "Deputante", "Matron", "Dandy", "La Reine", "Kabuki", "Pharaoh"};
                break;

            case 681: // Aegislash
                options = {"Shield", "Blade"};
                break;

            case 710: // Pumpkaboo
            case 711: // Gourgeist
                options = {"Average", "Small", "Large", "Super"};
                break;

            case 716: // Xerneas
                options = {"Neutral", "Active"};
                break;

            default:  // All Others
                options = {"Normal"};
                break;
        }
        return options;
    }

    static const char *allPkmn[721] = {
        "Bulbasaur",
        "Ivysaur",
        "Venusaur",
        "Charmander",
        "Charmeleon",
        "Charizard",
        "Squirtle",
        "Wartortle",
        "Blastoise",
        "Caterpie",
        "Metapod",
        "Butterfree",
        "Weedle",
        "Kakuna",
        "Beedrill",
        "Pidgey",
        "Pidgeotto",
        "Pidgeot",
        "Rattata",
        "Raticate",
        "Spearow",
        "Fearow",
        "Ekans",
        "Arbok",
        "Pikachu",
        "Raichu",
        "Sandshrew",
        "Sandslash",
        "NidoranF",
        "Nidorina",
        "Nidoqueen",
        "NidoranM",
        "Nidorino",
        "Nidoking",
        "Clefairy",
        "Clefable",
        "Vulpix",
        "Ninetales",
        "Jigglypuff",
        "Wigglytuff",
        "Zubat",
        "Golbat",
        "Oddish",
        "Gloom",
        "Vileplume",
        "Paras",
        "Parasect",
        "Venonat",
        "Venomoth",
        "Diglett",
        "Dugtrio",
        "Meowth",
        "Persian",
        "Psyduck",
        "Golduck",
        "Mankey",
        "Primeape",
        "Growlithe",
        "Arcanine",
        "Poliwag",
        "Poliwhirl",
        "Poliwrath",
        "Abra",
        "Kadabra",
        "Alakazam",
        "Machop",
        "Machoke",
        "Machamp",
        "Bellsprout",
        "Weepinbell",
        "Victreebel",
        "Tentacool",
        "Tentacruel",
        "Geodude",
        "Graveler",
        "Golem",
        "Ponyta",
        "Rapidash",
        "Slowpoke",
        "Slowbro",
        "Magnemite",
        "Magneton",
        "Farfetchd",
        "Doduo",
        "Dodrio",
        "Seel",
        "Dewgong",
        "Grimer",
        "Muk",
        "Shellder",
        "Cloyster",
        "Gastly",
        "Haunter",
        "Gengar",
        "Onix",
        "Drowzee",
        "Hypno",
        "Krabby",
        "Kingler",
        "Voltorb",
        "Electrode",
        "Exeggcute",
        "Exeggutor",
        "Cubone",
        "Marowak",
        "Hitmonlee",
        "Hitmonchan",
        "Lickitung",
        "Koffing",
        "Weezing",
        "Rhyhorn",
        "Rhydon",
        "Chansey",
        "Tangela",
        "Kangaskhan",
        "Horsea",
        "Seadra",
        "Goldeen",
        "Seaking",
        "Staryu",
        "Starmie",
        "MrMime",
        "Scyther",
        "Jynx",
        "Electabuzz",
        "Magmar",
        "Pinsir",
        "Tauros",
        "Magikarp",
        "Gyarados",
        "Lapras",
        "Ditto",
        "Eevee",
        "Vaporeon",
        "Jolteon",
        "Flareon",
        "Porygon",
        "Omanyte",
        "Omastar",
        "Kabuto",
        "Kabutops",
        "Aerodactyl",
        "Snorlax",
        "Articuno",
        "Zapdos",
        "Moltres",
        "Dratini",
        "Dragonair",
        "Dragonite",
        "Mewtwo",
        "Mew",
        "Chikorita",
        "Bayleef",
        "Meganium",
        "Cyndaquil",
        "Quilava",
        "Typhlosion",
        "Totodile",
        "Croconaw",
        "Feraligatr",
        "Sentret",
        "Furret",
        "Hoothoot",
        "Noctowl",
        "Ledyba",
        "Ledian",
        "Spinarak",
        "Ariados",
        "Crobat",
        "Chinchou",
        "Lanturn",
        "Pichu",
        "Cleffa",
        "Igglybuff",
        "Togepi",
        "Togetic",
        "Natu",
        "Xatu",
        "Mareep",
        "Flaaffy",
        "Ampharos",
        "Bellossom",
        "Marill",
        "Azumarill",
        "Sudowoodo",
        "Politoed",
        "Hoppip",
        "Skiploom",
        "Jumpluff",
        "Aipom",
        "Sunkern",
        "Sunflora",
        "Yanma",
        "Wooper",
        "Quagsire",
        "Espeon",
        "Umbreon",
        "Murkrow",
        "Slowking",
        "Misdreavus",
        "Unown",
        "Wobbuffet",
        "Girafarig",
        "Pineco",
        "Forretress",
        "Dunsparce",
        "Gligar",
        "Steelix",
        "Snubbull",
        "Granbull",
        "Qwilfish",
        "Scizor",
        "Shuckle",
        "Heracross",
        "Sneasel",
        "Teddiursa",
        "Ursaring",
        "Slugma",
        "Magcargo",
        "Swinub",
        "Piloswine",
        "Corsola",
        "Remoraid",
        "Octillery",
        "Delibird",
        "Mantine",
        "Skarmory",
        "Houndour",
        "Houndoom",
        "Kingdra",
        "Phanpy",
        "Donphan",
        "Porygon2",
        "Stantler",
        "Smeargle",
        "Tyrogue",
        "Hitmontop",
        "Smoochum",
        "Elekid",
        "Magby",
        "Miltank",
        "Blissey",
        "Raikou",
        "Entei",
        "Suicune",
        "Larvitar",
        "Pupitar",
        "Tyranitar",
        "Lugia",
        "HoOh",
        "Celebi",
        "Treecko",
        "Grovyle",
        "Sceptile",
        "Torchic",
        "Combusken",
        "Blaziken",
        "Mudkip",
        "Marshtomp",
        "Swampert",
        "Poochyena",
        "Mightyena",
        "Zigzagoon",
        "Linoone",
        "Wurmple",
        "Silcoon",
        "Beautifly",
        "Cascoon",
        "Dustox",
        "Lotad",
        "Lombre",
        "Ludicolo",
        "Seedot",
        "Nuzleaf",
        "Shiftry",
        "Taillow",
        "Swellow",
        "Wingull",
        "Pelipper",
        "Ralts",
        "Kirlia",
        "Gardevoir",
        "Surskit",
        "Masquerain",
        "Shroomish",
        "Breloom",
        "Slakoth",
        "Vigoroth",
        "Slaking",
        "Nincada",
        "Ninjask",
        "Shedinja",
        "Whismur",
        "Loudred",
        "Exploud",
        "Makuhita",
        "Hariyama",
        "Azurill",
        "Nosepass",
        "Skitty",
        "Delcatty",
        "Sableye",
        "Mawile",
        "Aron",
        "Lairon",
        "Aggron",
        "Meditite",
        "Medicham",
        "Electrike",
        "Manectric",
        "Plusle",
        "Minun",
        "Volbeat",
        "Illumise",
        "Roselia",
        "Gulpin",
        "Swalot",
        "Carvanha",
        "Sharpedo",
        "Wailmer",
        "Wailord",
        "Numel",
        "Camerupt",
        "Torkoal",
        "Spoink",
        "Grumpig",
        "Spinda",
        "Trapinch",
        "Vibrava",
        "Flygon",
        "Cacnea",
        "Cacturne",
        "Swablu",
        "Altaria",
        "Zangoose",
        "Seviper",
        "Lunatone",
        "Solrock",
        "Barboach",
        "Whiscash",
        "Corphish",
        "Crawdaunt",
        "Baltoy",
        "Claydol",
        "Lileep",
        "Cradily",
        "Anorith",
        "Armaldo",
        "Feebas",
        "Milotic",
        "Castform",
        "Kecleon",
        "Shuppet",
        "Banette",
        "Duskull",
        "Dusclops",
        "Tropius",
        "Chimecho",
        "Absol",
        "Wynaut",
        "Snorunt",
        "Glalie",
        "Spheal",
        "Sealeo",
        "Walrein",
        "Clamperl",
        "Huntail",
        "Gorebyss",
        "Relicanth",
        "Luvdisc",
        "Bagon",
        "Shelgon",
        "Salamence",
        "Beldum",
        "Metang",
        "Metagross",
        "Regirock",
        "Regice",
        "Registeel",
        "Latias",
        "Latios",
        "Kyogre",
        "Groudon",
        "Rayquaza",
        "Jirachi",
        "Deoxys",
        "Turtwig",
        "Grotle",
        "Torterra",
        "Chimchar",
        "Monferno",
        "Infernape",
        "Piplup",
        "Prinplup",
        "Empoleon",
        "Starly",
        "Staravia",
        "Staraptor",
        "Bidoof",
        "Bibarel",
        "Kricketot",
        "Kricketune",
        "Shinx",
        "Luxio",
        "Luxray",
        "Budew",
        "Roserade",
        "Cranidos",
        "Rampardos",
        "Shieldon",
        "Bastiodon",
        "Burmy",
        "Wormadam",
        "Mothim",
        "Combee",
        "Vespiquen",
        "Pachirisu",
        "Buizel",
        "Floatzel",
        "Cherubi",
        "Cherrim",
        "Shellos",
        "Gastrodon",
        "Ambipom",
        "Drifloon",
        "Drifblim",
        "Buneary",
        "Lopunny",
        "Mismagius",
        "Honchkrow",
        "Glameow",
        "Purugly",
        "Chingling",
        "Stunky",
        "Skuntank",
        "Bronzor",
        "Bronzong",
        "Bonsly",
        "MimeJr",
        "Happiny",
        "Chatot",
        "Spiritomb",
        "Gible",
        "Gabite",
        "Garchomp",
        "Munchlax",
        "Riolu",
        "Lucario",
        "Hippopotas",
        "Hippowdon",
        "Skorupi",
        "Drapion",
        "Croagunk",
        "Toxicroak",
        "Carnivine",
        "Finneon",
        "Lumineon",
        "Mantyke",
        "Snover",
        "Abomasnow",
        "Weavile",
        "Magnezone",
        "Lickilicky",
        "Rhyperior",
        "Tangrowth",
        "Electivire",
        "Magmortar",
        "Togekiss",
        "Yanmega",
        "Leafeon",
        "Glaceon",
        "Gliscor",
        "Mamoswine",
        "PorygonZ",
        "Gallade",
        "Probopass",
        "Dusknoir",
        "Froslass",
        "Rotom",
        "Uxie",
        "Mesprit",
        "Azelf",
        "Dialga",
        "Palkia",
        "Heatran",
        "Regigigas",
        "Giratina",
        "Cresselia",
        "Phione",
        "Manaphy",
        "Darkrai",
        "Shaymin",
        "Arceus",
        "Victini",
        "Snivy",
        "Servine",
        "Serperior",
        "Tepig",
        "Pignite",
        "Emboar",
        "Oshawott",
        "Dewott",
        "Samurott",
        "Patrat",
        "Watchog",
        "Lillipup",
        "Herdier",
        "Stoutland",
        "Purrloin",
        "Liepard",
        "Pansage",
        "Simisage",
        "Pansear",
        "Simisear",
        "Panpour",
        "Simipour",
        "Munna",
        "Musharna",
        "Pidove",
        "Tranquill",
        "Unfezant",
        "Blitzle",
        "Zebstrika",
        "Roggenrola",
        "Boldore",
        "Gigalith",
        "Woobat",
        "Swoobat",
        "Drilbur",
        "Excadrill",
        "Audino",
        "Timburr",
        "Gurdurr",
        "Conkeldurr",
        "Tympole",
        "Palpitoad",
        "Seismitoad",
        "Throh",
        "Sawk",
        "Sewaddle",
        "Swadloon",
        "Leavanny",
        "Venipede",
        "Whirlipede",
        "Scolipede",
        "Cottonee",
        "Whimsicott",
        "Petilil",
        "Lilligant",
        "Basculin",
        "Sandile",
        "Krokorok",
        "Krookodile",
        "Darumaka",
        "Darmanitan",
        "Maractus",
        "Dwebble",
        "Crustle",
        "Scraggy",
        "Scrafty",
        "Sigilyph",
        "Yamask",
        "Cofagrigus",
        "Tirtouga",
        "Carracosta",
        "Archen",
        "Archeops",
        "Trubbish",
        "Garbodor",
        "Zorua",
        "Zoroark",
        "Minccino",
        "Cinccino",
        "Gothita",
        "Gothorita",
        "Gothitelle",
        "Solosis",
        "Duosion",
        "Reuniclus",
        "Ducklett",
        "Swanna",
        "Vanillite",
        "Vanillish",
        "Vanilluxe",
        "Deerling",
        "Sawsbuck",
        "Emolga",
        "Karrablast",
        "Escavalier",
        "Foongus",
        "Amoonguss",
        "Frillish",
        "Jellicent",
        "Alomomola",
        "Joltik",
        "Galvantula",
        "Ferroseed",
        "Ferrothorn",
        "Klink",
        "Klang",
        "Klinklang",
        "Tynamo",
        "Eelektrik",
        "Eelektross",
        "Elgyem",
        "Beheeyem",
        "Litwick",
        "Lampent",
        "Chandelure",
        "Axew",
        "Fraxure",
        "Haxorus",
        "Cubchoo",
        "Beartic",
        "Cryogonal",
        "Shelmet",
        "Accelgor",
        "Stunfisk",
        "Mienfoo",
        "Mienshao",
        "Druddigon",
        "Golett",
        "Golurk",
        "Pawniard",
        "Bisharp",
        "Bouffalant",
        "Rufflet",
        "Braviary",
        "Vullaby",
        "Mandibuzz",
        "Heatmor",
        "Durant",
        "Deino",
        "Zweilous",
        "Hydreigon",
        "Larvesta",
        "Volcarona",
        "Cobalion",
        "Terrakion",
        "Virizion",
        "Tornadus",
        "Thundurus",
        "Reshiram",
        "Zekrom",
        "Landorus",
        "Kyurem",
        "Keldeo",
        "Meloetta",
        "Genesect",
        "Chespin",
        "Quilladin",
        "Chesnaught",
        "Fennekin",
        "Braixen",
        "Delphox",
        "Froakie",
        "Frogadier",
        "Greninja",
        "Bunnelby",
        "Diggersby",
        "Fletchling",
        "Fletchinder",
        "Talonflame",
        "Scatterbug",
        "Spewpa",
        "Vivillon",
        "Litleo",
        "Pyroar",
        "Flabébé",
        "Floette",
        "Florges",
        "Skiddo",
        "Gogoat",
        "Pancham",
        "Pangoro",
        "Furfrou",
        "Espurr",
        "Meowstic",
        "Honedge",
        "Doublade",
        "Aegislash",
        "Spritzee",
        "Aromatisse",
        "Swirlix",
        "Slurpuff",
        "Inkay",
        "Malamar",
        "Binacle",
        "Barbaracle",
        "Skrelp",
        "Dragalge",
        "Clauncher",
        "Clawitzer",
        "Helioptile",
        "Heliolisk",
        "Tyrunt",
        "Tyrantrum",
        "Amaura",
        "Aurorus",
        "Sylveon",
        "Hawlucha",
        "Dedenne",
        "Carbink",
        "Goomy",
        "Sliggoo",
        "Goodra",
        "Klefki",
        "Phantump",
        "Trevenant",
        "Pumpkaboo",
        "Gourgeist",
        "Bergmite",
        "Avalugg",
        "Noibat",
        "Noivern",
        "Xerneas",
        "Yveltal",
        "Zygarde",
        "Diancie",
        "Hoopa",
        "Volcanion"
    };

    extern int pkmnID;

    struct Pokemon {
        StringVector name;
        vector<int> choiceNo;
    };

    void SelectAPokemon(MenuEntry *entry);

    static const StringVector allNatures = {
        "Hardy",
        "Lonely",
        "Brave",
        "Adamant",
        "Naughty",
        "Bold",
        "Docile",
        "Relaxed",
        "Impish",
        "Lax",
        "Timid",
        "Hasty",
        "Serious",
        "Jolly",
        "Naive",
        "Modest",
        "Mild",
        "Quiet",
        "Bashful",
        "Rash",
        "Calm",
        "Gentle",
        "Sassy",
        "Careful",
        "Quirky"
    };

    static const char *allAbilities[234] = {
        "None",
        "Stench",
        "Drizzle",
        "Speed Boost",
        "Battle Armor",
        "Sturdy",
        "Damp",
        "Limber",
        "Sand Veil",
        "Static",
        "Volt Absorb",
        "Water Absorb",
        "Oblivious",
        "Cloud Nine",
        "Compound Eyes",
        "Insomnia",
        "Color Change",
        "Immunity",
        "Flash Fire",
        "Shield Dust",
        "Own Tempo",
        "Suction Cups",
        "Intimidate",
        "Shadow Tag",
        "Rough Skin",
        "Wonder Guard",
        "Levitate",
        "Effect Spore",
        "Synchronize",
        "Clear Body",
        "Natural Cure",
        "Lightning Rod",
        "Serene Grace",
        "Swift Swim",
        "Chlorophyll",
        "Illuminate",
        "Trace",
        "Huge Power",
        "Poison Point",
        "Inner Focus",
        "Magma Armor",
        "Water Veil",
        "Magnet Pull",
        "Soundproof",
        "Rain Dish",
        "Sand Stream",
        "Pressure",
        "Thick Fat",
        "Early Bird",
        "Flame Body",
        "Run Away",
        "Keen Eye",
        "Hyper Cutter",
        "Pickup",
        "Truant",
        "Hustle",
        "Cute Charm",
        "Plus",
        "Minus",
        "Forecast",
        "Sticky Hold",
        "Shed Skin",
        "Guts",
        "Marvel Scale",
        "Liquid Ooze",
        "Overgrow",
        "Blaze",
        "Torrent",
        "Swarm",
        "Rock Head",
        "Drought",
        "Arena Trap",
        "Vital Spirit",
        "White Smoke",
        "Pure Power",
        "Shell Armor",
        "Air Lock",
        "Tangled Feet",
        "Motor Drive",
        "Rivalry",
        "Steadfast",
        "Snow Cloak",
        "Gluttony",
        "Anger Point",
        "Unburden",
        "Heatproof",
        "Simple",
        "Dry Skin",
        "Download",
        "Iron Fist",
        "Poison Heal",
        "Adaptability",
        "Skill Link",
        "Hydration",
        "Solar Power",
        "Quick Feet",
        "Normalize",
        "Sniper",
        "Magic Guard",
        "No Guard",
        "Stall",
        "Technician",
        "Leaf Guard",
        "Klutz",
        "Mold Breaker",
        "Super Luck",
        "Aftermath",
        "Anticipation",
        "Forewarn",
        "Unaware",
        "Tinted Lens",
        "Filter",
        "Slow Start",
        "Scrappy",
        "Storm Drain",
        "Ice Body",
        "Solid Rock",
        "Snow Warning",
        "Honey Gather",
        "Frisk",
        "Reckless",
        "Multitype",
        "Flower Gift",
        "Bad Dreams",
        "Pickpocket",
        "Sheer Force",
        "Contrary",
        "Unnerve",
        "Defiant",
        "Defeatist",
        "Cursed Body",
        "Healer",
        "Friend Guard",
        "Weak Armor",
        "Heavy Metal",
        "Light Metal",
        "Multiscale",
        "Toxic Boost",
        "Flare Boost",
        "Harvest",
        "Telepathy",
        "Moody",
        "Overcoat",
        "Poison Touch",
        "Regenerator",
        "Big Pecks",
        "Sand Rush",
        "Wonder Skin",
        "Analytic",
        "Illusion",
        "Imposter",
        "Infiltrator",
        "Mummy",
        "Moxie",
        "Justified",
        "Rattled",
        "Magic Bounce",
        "Sap Sipper",
        "Prankster",
        "Sand Force",
        "Iron Barbs",
        "Zen Mode",
        "Victory Star",
        "Turboblaze",
        "Teravolt",
        "Aroma Veil",
        "Flower Veil",
        "Cheek Pouch",
        "Protean",
        "Fur Coat",
        "Magician",
        "Bulletproof",
        "Competitive",
        "Strong Jaw",
        "Refrigerate",
        "Sweet Veil",
        "Stance Change",
        "Gale Wings",
        "Mega Launcher",
        "Grass Pelt",
        "Symbiosis",
        "Tough Claws",
        "Pixilate",
        "Gooey",
        "Aerilate",
        "Parental Bond",
        "Dark Aura",
        "Fairy Aura",
        "Aura Break",
        "Primordial Sea",
        "Desolate Land",
        "Delta Stream",
        "Stamina",
        "Wimp Out",
        "Emergency Exit",
        "Water Compaction",
        "Merciless",
        "Shields Down",
        "Stakeout",
        "Water Bubble",
        "Steelworker",
        "Berserk",
        "Slush Rush",
        "Long Reach",
        "Liquid Voice",
        "Triage",
        "Galvanize",
        "Surge Surfer",
        "Schooling",
        "Disguise",
        "Battle Bond",
        "Power Construct",
        "Corrosion",
        "Comatose",
        "Queenly Majesty",
        "Innards Out",
        "Dancer",
        "Battery",
        "Fluffy",
        "Dazzling",
        "Soul-Heart",
        "Tangling Hair",
        "Receiver",
        "Power of Alchemy",
        "Beast Boost",
        "RKS System",
        "Electric Surge",
        "Psychic Surge",
        "Misty Surge",
        "Grassy Surge",
        "Full Metal Body",
        "Shadow Shield",
        "Prism Armor",
        "Neuroforce"
    };

    extern int abilityID;

    struct Ability {
        StringVector name;
        vector<int> choiceNo;
    };

    void SelectAnAbility(MenuEntry *entry);

    static const char *allHeldItems[960] = {
        "None",
        "Master Ball",
        "Ultra Ball",
        "Great Ball",
        "Poké Ball",
        "Safari Ball",
        "Net Ball",
        "Dive Ball",
        "Nest Ball",
        "Repeat Ball",
        "Timer Ball",
        "Luxury Ball",
        "Premier Ball",
        "Dusk Ball",
        "Heal Ball",
        "Quick Ball",
        "Cherish Ball",
        "Potion",
        "Antidote",
        "Burn Heal",
        "Ice Heal",
        "Awakening",
        "Paralyze Heal",
        "Full Restore",
        "Max Potion",
        "Hyper Potion",
        "Super Potion",
        "Full Heal",
        "Revive",
        "Max Revive",
        "Fresh Water",
        "Soda Pop",
        "Lemonade",
        "Moomoo Milk",
        "Energy Powder",
        "Energy Root",
        "Heal Powder",
        "Revival Herb",
        "Ether",
        "Max Ether",
        "Elixir",
        "Max Elixir",
        "Lava Cookie",
        "Berry Juice",
        "Sacred Ash",
        "HP Up",
        "Protein",
        "Iron",
        "Carbos",
        "Calcium",
        "Rare Candy",
        "PP Up",
        "Zinc",
        "PP Max",
        "Old Gateau",
        "Guard Spec.",
        "Dire Hit",
        "X Attack",
        "X Defense",
        "X Speed",
        "X Accuracy",
        "X Sp. Atk",
        "X Sp. Def",
        "Poké Doll",
        "Fluffy Tail",
        "Blue Flute",
        "Yellow Flute",
        "Red Flute",
        "Black Flute",
        "White Flute",
        "Shoal Salt",
        "Shoal Shell",
        "Red Shard",
        "Blue Shard",
        "Yellow Shard",
        "Green Shard",
        "Super Repel",
        "Max Repel",
        "Escape Rope",
        "Repel",
        "Sun Stone",
        "Moon Stone",
        "Fire Stone",
        "Thunder Stone",
        "Water Stone",
        "Leaf Stone",
        "Tiny Mushroom",
        "Big Mushroom",
        "Pearl",
        "Big Pearl",
        "Stardust",
        "Star Piece",
        "Nugget",
        "Heart Scale",
        "Honey",
        "Growth Mulch",
        "Damp Mulch",
        "Stable Mulch",
        "Gooey Mulch",
        "Root Fossil",
        "Claw Fossil",
        "Helix Fossil",
        "Dome Fossil",
        "Old Amber",
        "Armor Fossil",
        "Skull Fossil",
        "Rare Bone",
        "Shiny Stone",
        "Dusk Stone",
        "Dawn Stone",
        "Oval Stone",
        "Odd Keystone",
        "Griseous Orb",
        "Tea",
        "???",
        "Autograph",
        "Douse Drive",
        "Shock Drive",
        "Burn Drive",
        "Chill Drive",
        "???",
        "Pokémon Box Link",
        "Medicine Pocket",
        "TM Case",
        "Candy Jar",
        "Power-Up Pocket",
        "Clothing Trunk",
        "Catching Pocket",
        "Battle Pocket",
        "???",
        "???",
        "???",
        "???",
        "???",
        "Sweet Heart",
        "Adamant Orb",
        "Lustrous Orb",
        "Greet Mail",
        "Favored Mail",
        "RSVP Mail",
        "Thanks Mail",
        "Inquiry Mail",
        "Like Mail",
        "Reply Mail",
        "Bridge Mail S",
        "Bridge Mail D",
        "Bridge Mail T",
        "Bridge Mail V",
        "Bridge Mail M",
        "Cheri Berry",
        "Chesto Berry",
        "Pecha Berry",
        "Rawst Berry",
        "Aspear Berry",
        "Leppa Berry",
        "Oran Berry",
        "Persim Berry",
        "Lum Berry",
        "Sitrus Berry",
        "Figy Berry",
        "Wiki Berry",
        "Mago Berry",
        "Aguav Berry",
        "Iapapa Berry",
        "Razz Berry",
        "Bluk Berry",
        "Nanab Berry",
        "Wepear Berry",
        "Pinap Berry",
        "Pomeg Berry",
        "Kelpsy Berry",
        "Qualot Berry",
        "Hondew Berry",
        "Grepa Berry",
        "Tamato Berry",
        "Cornn Berry",
        "Magost Berry",
        "Rabuta Berry",
        "Nomel Berry",
        "Spelon Berry",
        "Pamtre Berry",
        "Watmel Berry",
        "Durin Berry",
        "Belue Berry",
        "Occa Berry",
        "Passho Berry",
        "Wacan Berry",
        "Rindo Berry",
        "Yache Berry",
        "Chople Berry",
        "Kebia Berry",
        "Shuca Berry",
        "Coba Berry",
        "Payapa Berry",
        "Tanga Berry",
        "Charti Berry",
        "Kasib Berry",
        "Haban Berry",
        "Colbur Berry",
        "Babiri Berry",
        "Chilan Berry",
        "Liechi Berry",
        "Ganlon Berry",
        "Salac Berry",
        "Petaya Berry",
        "Apicot Berry",
        "Lansat Berry",
        "Starf Berry",
        "Enigma Berry",
        "Micle Berry",
        "Custap Berry",
        "Jaboca Berry",
        "Rowap Berry",
        "Bright Powder",
        "White Herb",
        "Macho Brace",
        "Exp. Share",
        "Quick Claw",
        "Soothe Bell",
        "Mental Herb",
        "Choice Band",
        "King’s Rock",
        "Silver Powder",
        "Amulet Coin",
        "Cleanse Tag",
        "Soul Dew",
        "Deep Sea Tooth",
        "Deep Sea Scale",
        "Smoke Ball",
        "Everstone",
        "Focus Band",
        "Lucky Egg",
        "Scope Lens",
        "Metal Coat",
        "Leftovers",
        "Dragon Scale",
        "Light Ball",
        "Soft Sand",
        "Hard Stone",
        "Miracle Seed",
        "Black Glasses",
        "Black Belt",
        "Magnet",
        "Mystic Water",
        "Sharp Beak",
        "Poison Barb",
        "Never-Melt Ice",
        "Spell Tag",
        "Twisted Spoon",
        "Charcoal",
        "Dragon Fang",
        "Silk Scarf",
        "Upgrade",
        "Shell Bell",
        "Sea Incense",
        "Lax Incense",
        "Lucky Punch",
        "Metal Powder",
        "Thick Club",
        "Leek",
        "Red Scarf",
        "Blue Scarf",
        "Pink Scarf",
        "Green Scarf",
        "Yellow Scarf",
        "Wide Lens",
        "Muscle Band",
        "Wise Glasses",
        "Expert Belt",
        "Light Clay",
        "Life Orb",
        "Power Herb",
        "Toxic Orb",
        "Flame Orb",
        "Quick Powder",
        "Focus Sash",
        "Zoom Lens",
        "Metronome",
        "Iron Ball",
        "Lagging Tail",
        "Destiny Knot",
        "Black Sludge",
        "Icy Rock",
        "Smooth Rock",
        "Heat Rock",
        "Damp Rock",
        "Grip Claw",
        "Choice Scarf",
        "Sticky Barb",
        "Power Bracer",
        "Power Belt",
        "Power Lens",
        "Power Band",
        "Power Anklet",
        "Power Weight",
        "Shed Shell",
        "Big Root",
        "Choice Specs",
        "Flame Plate",
        "Splash Plate",
        "Zap Plate",
        "Meadow Plate",
        "Icicle Plate",
        "Fist Plate",
        "Toxic Plate",
        "Earth Plate",
        "Sky Plate",
        "Mind Plate",
        "Insect Plate",
        "Stone Plate",
        "Spooky Plate",
        "Draco Plate",
        "Dread Plate",
        "Iron Plate",
        "Odd Incense",
        "Rock Incense",
        "Full Incense",
        "Wave Incense",
        "Rose Incense",
        "Luck Incense",
        "Pure Incense",
        "Protector",
        "Electirizer",
        "Magmarizer",
        "Dubious Disc",
        "Reaper Cloth",
        "Razor Claw",
        "Razor Fang",
        "TM01",
        "TM02",
        "TM03",
        "TM04",
        "TM05",
        "TM06",
        "TM07",
        "TM08",
        "TM09",
        "TM10",
        "TM11",
        "TM12",
        "TM13",
        "TM14",
        "TM15",
        "TM16",
        "TM17",
        "TM18",
        "TM19",
        "TM20",
        "TM21",
        "TM22",
        "TM23",
        "TM24",
        "TM25",
        "TM26",
        "TM27",
        "TM28",
        "TM29",
        "TM30",
        "TM31",
        "TM32",
        "TM33",
        "TM34",
        "TM35",
        "TM36",
        "TM37",
        "TM38",
        "TM39",
        "TM40",
        "TM41",
        "TM42",
        "TM43",
        "TM44",
        "TM45",
        "TM46",
        "TM47",
        "TM48",
        "TM49",
        "TM50",
        "TM51",
        "TM52",
        "TM53",
        "TM54",
        "TM55",
        "TM56",
        "TM57",
        "TM58",
        "TM59",
        "TM60",
        "TM61",
        "TM62",
        "TM63",
        "TM64",
        "TM65",
        "TM66",
        "TM67",
        "TM68",
        "TM69",
        "TM70",
        "TM71",
        "TM72",
        "TM73",
        "TM74",
        "TM75",
        "TM76",
        "TM77",
        "TM78",
        "TM79",
        "TM80",
        "TM81",
        "TM82",
        "TM83",
        "TM84",
        "TM85",
        "TM86",
        "TM87",
        "TM88",
        "TM89",
        "TM90",
        "TM91",
        "TM92",
        "HM01",
        "HM02",
        "HM03",
        "HM04",
        "HM05",
        "HM06",
        "???",
        "???",
        "Explorer Kit",
        "Loot Sack",
        "Rule Book",
        "Poké Radar",
        "Point Card",
        "Journal",
        "Seal Case",
        "Fashion Case",
        "Seal Bag",
        "Pal Pad",
        "Works Key",
        "Old Charm",
        "Galactic Key",
        "Red Chain",
        "Town Map",
        "Vs. Seeker",
        "Coin Case",
        "Old Rod",
        "Good Rod",
        "Super Rod",
        "Sprayduck",
        "Poffin Case",
        "Bike",
        "Suite Key",
        "Oak’s Letter",
        "Lunar Wing",
        "Member Card",
        "Azure Flute",
        "S.S. Ticket",
        "Contest Pass",
        "Magma Stone",
        "Parcel",
        "Coupon 1",
        "Coupon 2",
        "Coupon 3",
        "Storage Key",
        "Secret Potion",
        "Vs. Recorder",
        "Gracidea",
        "Secret Key",
        "Apricorn Box",
        "Unown Report",
        "Berry Pots",
        "Dowsing Machine",
        "Blue Card",
        "Slowpoke Tail",
        "Clear Bell",
        "Card Key",
        "Basement Key",
        "Squirt Bottle",
        "Red Scale",
        "Lost Item",
        "Pass",
        "Machine Part",
        "Silver Wing",
        "Rainbow Wing",
        "Mystery Egg",
        "Red Apricorn",
        "Blue Apricorn",
        "Yellow Apricorn",
        "Green Apricorn",
        "Pink Apricorn",
        "White Apricorn",
        "Black Apricorn",
        "Fast Ball",
        "Level Ball",
        "Lure Ball",
        "Heavy Ball",
        "Love Ball",
        "Friend Ball",
        "Moon Ball",
        "Sport Ball",
        "Park Ball",
        "Photo Album",
        "GB Sounds",
        "Tidal Bell",
        "Rage Candy Bar",
        "Data Card 01",
        "Data Card 02",
        "Data Card 03",
        "Data Card 04",
        "Data Card 05",
        "Data Card 06",
        "Data Card 07",
        "Data Card 08",
        "Data Card 09",
        "Data Card 10",
        "Data Card 11",
        "Data Card 12",
        "Data Card 13",
        "Data Card 14",
        "Data Card 15",
        "Data Card 16",
        "Data Card 17",
        "Data Card 18",
        "Data Card 19",
        "Data Card 20",
        "Data Card 21",
        "Data Card 22",
        "Data Card 23",
        "Data Card 24",
        "Data Card 25",
        "Data Card 26",
        "Data Card 27",
        "Jade Orb",
        "Lock Capsule",
        "Red Orb",
        "Blue Orb",
        "Enigma Stone",
        "Prism Scale",
        "Eviolite",
        "Float Stone",
        "Rocky Helmet",
        "Air Balloon",
        "Red Card",
        "Ring Target",
        "Binding Band",
        "Absorb Bulb",
        "Cell Battery",
        "Eject Button",
        "Fire Gem",
        "Water Gem",
        "Electric Gem",
        "Grass Gem",
        "Ice Gem",
        "Fighting Gem",
        "Poison Gem",
        "Ground Gem",
        "Flying Gem",
        "Psychic Gem",
        "Bug Gem",
        "Rock Gem",
        "Ghost Gem",
        "Dragon Gem",
        "Dark Gem",
        "Steel Gem",
        "Normal Gem",
        "Health Feather",
        "Muscle Feather",
        "Resist Feather",
        "Genius Feather",
        "Clever Feather",
        "Swift Feather",
        "Pretty Feather",
        "Cover Fossil",
        "Plume Fossil",
        "Liberty Pass",
        "Pass Orb",
        "Dream Ball",
        "Poké Toy",
        "Prop Case",
        "Dragon Skull",
        "Balm Mushroom",
        "Big Nugget",
        "Pearl String",
        "Comet Shard",
        "Relic Copper",
        "Relic Silver",
        "Relic Gold",
        "Relic Vase",
        "Relic Band",
        "Relic Statue",
        "Relic Crown",
        "Casteliacone",
        "Dire Hit 2",
        "X Speed 2",
        "X Sp. Atk 2",
        "X Sp. Def 2",
        "X Defense 2",
        "X Attack 2",
        "X Accuracy 2",
        "X Speed 3",
        "X Sp. Atk 3",
        "X Sp. Def 3",
        "X Defense 3",
        "X Attack 3",
        "X Accuracy 3",
        "X Speed 6",
        "X Sp. Atk 6",
        "X Sp. Def 6",
        "X Defense 6",
        "X Attack 6",
        "X Accuracy 6",
        "Ability Urge",
        "Item Drop",
        "Item Urge",
        "Reset Urge",
        "Dire Hit 3",
        "Light Stone",
        "Dark Stone",
        "TM93",
        "TM94",
        "TM95",
        "Xtransceiver",
        "???",
        "Gram 1",
        "Gram 2",
        "Gram 3",
        "Xtransceiver",
        "Medal Box",
        "DNA Splicers",
        "DNA Splicers",
        "Permit",
        "Oval Charm",
        "Shiny Charm",
        "Plasma Card",
        "Grubby Hanky",
        "Colress Machine",
        "Dropped Item",
        "Dropped Item",
        "Reveal Glass",
        "Weakness Policy",
        "Assault Vest",
        "Holo Caster",
        "Prof’s Letter",
        "Roller Skates",
        "Pixie Plate",
        "Ability Capsule",
        "Whipped Dream",
        "Sachet",
        "Luminous Moss",
        "Snowball",
        "Safety Goggles",
        "Poké Flute",
        "Rich Mulch",
        "Surprise Mulch",
        "Boost Mulch",
        "Amaze Mulch",
        "Gengarite",
        "Gardevoirite",
        "Ampharosite",
        "Venusaurite",
        "Charizardite X",
        "Blastoisinite",
        "Mewtwonite X",
        "Mewtwonite Y",
        "Blazikenite",
        "Medichamite",
        "Houndoominite",
        "Aggronite",
        "Banettite",
        "Tyranitarite",
        "Scizorite",
        "Pinsirite",
        "Aerodactylite",
        "Lucarionite",
        "Abomasite",
        "Kangaskhanite",
        "Gyaradosite",
        "Absolite",
        "Charizardite Y",
        "Alakazite",
        "Heracronite",
        "Mawilite",
        "Manectite",
        "Garchompite",
        "Latiasite",
        "Latiosite",
        "Roseli Berry",
        "Kee Berry",
        "Maranga Berry",
        "Sprinklotad",
        "TM96",
        "TM97",
        "TM98",
        "TM99",
        "TM100",
        "Power Plant Pass",
        "Mega Ring",
        "Intriguing Stone",
        "Common Stone",
        "Discount Coupon",
        "Elevator Key",
        "TMV Pass",
        "Honor of Kalos",
        "Adventure Guide",
        "Strange Souvenir",
        "Lens Case",
        "Makeup Bag",
        "Travel Trunk",
        "Lumiose Galette",
        "Shalour Sable",
        "Jaw Fossil",
        "Sail Fossil",
        "Looker Ticket",
        "Bike",
        "Holo Caster",
        "Fairy Gem",
        "Mega Charm",
        "Mega Glove",
        "Mach Bike",
        "Acro Bike",
        "Wailmer Pail",
        "Devon Parts",
        "Soot Sack",
        "Basement Key",
        "Pokéblock Kit",
        "Letter",
        "Eon Ticket",
        "Scanner",
        "Go-Goggles",
        "Meteorite",
        "Key to Room 1",
        "Key to Room 2",
        "Key to Room 4",
        "Key to Room 6",
        "Storage Key",
        "Devon Scope",
        "S.S. Ticket",
        "HM07",
        "Devon Scuba Gear",
        "Contest Costume",
        "Contest Costume",
        "Magma Suit",
        "Aqua Suit",
        "Pair of Tickets",
        "Mega Bracelet",
        "Mega Pendant",
        "Mega Glasses",
        "Mega Anchor",
        "Mega Stickpin",
        "Mega Tiara",
        "Mega Anklet",
        "Meteorite",
        "Swampertite",
        "Sceptilite",
        "Sablenite",
        "Altarianite",
        "Galladite",
        "Audinite",
        "Metagrossite",
        "Sharpedonite",
        "Slowbronite",
        "Steelixite",
        "Pidgeotite",
        "Glalitite",
        "Diancite",
        "Prison Bottle",
        "Mega Cuff",
        "Cameruptite",
        "Lopunnite",
        "Salamencite",
        "Beedrillite",
        "Meteorite",
        "Meteorite",
        "Key Stone",
        "Meteorite Shard",
        "Eon Flute",
        "Normalium Z",
        "Firium Z",
        "Waterium Z",
        "Electrium Z",
        "Grassium Z",
        "Icium Z",
        "Fightinium Z",
        "Poisonium Z",
        "Groundium Z",
        "Flyinium Z",
        "Psychium Z",
        "Buginium Z",
        "Rockium Z",
        "Ghostium Z",
        "Dragonium Z",
        "Darkinium Z",
        "Steelium Z",
        "Fairium Z",
        "Pikanium Z",
        "Bottle Cap",
        "Gold Bottle Cap",
        "Z-Ring",
        "Decidium Z",
        "Incinium Z",
        "Primarium Z",
        "Tapunium Z",
        "Marshadium Z",
        "Aloraichium Z",
        "Snorlium Z",
        "Eevium Z",
        "Mewnium Z",
        "Normalium Z",
        "Firium Z",
        "Waterium Z",
        "Electrium Z",
        "Grassium Z",
        "Icium Z",
        "Fightinium Z",
        "Poisonium Z",
        "Groundium Z",
        "Flyinium Z",
        "Psychium Z",
        "Buginium Z",
        "Rockium Z",
        "Ghostium Z",
        "Dragonium Z",
        "Darkinium Z",
        "Steelium Z",
        "Fairium Z",
        "Pikanium Z",
        "Decidium Z",
        "Incinium Z",
        "Primarium Z",
        "Tapunium Z",
        "Marshadium Z",
        "Aloraichium Z",
        "Snorlium Z",
        "Eevium Z",
        "Mewnium Z",
        "Pikashunium Z",
        "Pikashunium Z",
        "???",
        "???",
        "???",
        "???",
        "Forage Bag",
        "Fishing Rod",
        "Professor’s Mask",
        "Festival Ticket",
        "Sparkling Stone",
        "Adrenaline Orb",
        "Zygarde Cube",
        "???",
        "Ice Stone",
        "Ride Pager",
        "Beast Ball",
        "Big Malasada",
        "Red Nectar",
        "Yellow Nectar",
        "Pink Nectar",
        "Purple Nectar",
        "Sun Flute",
        "Moon Flute",
        "???",
        "Enigmatic Card",
        "Silver Razz Berry",
        "Golden Razz Berry",
        "Silver Nanab Berry",
        "Golden Nanab Berry",
        "Silver Pinap Berry",
        "Golden Pinap Berry",
        "???",
        "???",
        "???",
        "???",
        "???",
        "Secret Key",
        "S.S. Ticket",
        "Silph Scope",
        "Parcel",
        "Card Key",
        "Gold Teeth",
        "Lift Key",
        "Terrain Extender",
        "Protective Pads",
        "Electric Seed",
        "Psychic Seed",
        "Misty Seed",
        "Grassy Seed",
        "Stretchy Spring",
        "Chalky Stone",
        "Marble",
        "Lone Earring",
        "Beach Glass",
        "Gold Leaf",
        "Silver Leaf",
        "Polished Mud Ball",
        "Tropical Shell",
        "Leaf Letter",
        "Leaf Letter",
        "Small Bouquet",
        "???",
        "???",
        "???",
        "Lure",
        "Super Lure",
        "Max Lure",
        "Pewter Crunchies",
        "Fighting Memory",
        "Flying Memory",
        "Poison Memory",
        "Ground Memory",
        "Rock Memory",
        "Bug Memory",
        "Ghost Memory",
        "Steel Memory",
        "Fire Memory",
        "Water Memory",
        "Grass Memory",
        "Electric Memory",
        "Psychic Memory",
        "Ice Memory",
        "Dragon Memory",
        "Dark Memory",
        "Fairy Memory",
        "Solganium Z",
        "Lunalium Z",
        "Ultranecrozium Z",
        "Mimikium Z",
        "Lycanium Z",
        "Kommonium Z",
        "Solganium Z",
        "Lunalium Z",
        "Ultranecrozium Z",
        "Mimikium Z",
        "Lycanium Z",
        "Kommonium Z",
        "Z-Power Ring",
        "Pink Petal",
        "Orange Petal",
        "Blue Petal",
        "Red Petal",
        "Green Petal",
        "Yellow Petal",
        "Purple Petal",
        "Rainbow Flower",
        "Surge Badge",
        "N-Solarizer",
        "N-Lunarizer",
        "N-Solarizer",
        "N-Lunarizer",
        "Ilima Normalium Z",
        "Left Poké Ball",
        "Roto Hatch",
        "Roto Bargain",
        "Roto Prize Money",
        "Roto Exp. Points",
        "Roto Friendship",
        "Roto Encounter",
        "Roto Stealth",
        "Roto HP Restore",
        "Roto PP Restore",
        "Roto Boost",
        "Roto Catch"
    };

    extern int heldItemID;

    struct HeldItem {
        StringVector name;
        vector<int> choiceNo;
    };

    void SelectAHeldItem(MenuEntry *entry);

    static const char *allMoves[743] = {
        "None",
        "Pound",
        "Karate Chop",
        "Double Slap",
        "Comet Punch",
        "Mega Punch",
        "Pay Day",
        "Fire Punch",
        "Ice Punch",
        "Thunder Punch",
        "Scratch",
        "Vise Grip",
        "Guillotine",
        "Razor Wind",
        "Swords Dance",
        "Cut",
        "Gust",
        "Wing Attack",
        "Whirlwind",
        "Fly",
        "Bind",
        "Slam",
        "Vine Whip",
        "Stomp",
        "Double Kick",
        "Mega Kick",
        "Jump Kick",
        "Rolling Kick",
        "Sand Attack",
        "Headbutt",
        "Horn Attack",
        "Fury Attack",
        "Horn Drill",
        "Tackle",
        "Body Slam",
        "Wrap",
        "Take Down",
        "Thrash",
        "Double-Edge",
        "Tail Whip",
        "Poison Sting",
        "Twineedle",
        "Pin Missile",
        "Leer",
        "Bite",
        "Growl",
        "Roar",
        "Sing",
        "Supersonic",
        "Sonic Boom",
        "Disable",
        "Acid",
        "Ember",
        "Flamethrower",
        "Mist",
        "Water Gun",
        "Hydro Pump",
        "Surf",
        "Ice Beam",
        "Blizzard",
        "Psybeam",
        "Bubble Beam",
        "Aurora Beam",
        "Hyper Beam",
        "Peck",
        "Drill Peck",
        "Submission",
        "Low Kick",
        "Counter",
        "Seismic Toss",
        "Strength",
        "Absorb",
        "Mega Drain",
        "Leech Seed",
        "Growth",
        "Razor Leaf",
        "Solar Beam",
        "Poison Powder",
        "Stun Spore",
        "Sleep Powder",
        "Petal Dance",
        "String Shot",
        "Dragon Rage",
        "Fire Spin",
        "Thunder Shock",
        "Thunderbolt",
        "Thunder Wave",
        "Thunder",
        "Rock Throw",
        "Earthquake",
        "Fissure",
        "Dig",
        "Toxic",
        "Confusion",
        "Psychic",
        "Hypnosis",
        "Meditate",
        "Agility",
        "Quick Attack",
        "Rage",
        "Teleport",
        "Night Shade",
        "Mimic",
        "Screech",
        "Double Team",
        "Recover",
        "Harden",
        "Minimize",
        "Smokescreen",
        "Confuse Ray",
        "Withdraw",
        "Defense Curl",
        "Barrier",
        "Light Screen",
        "Haze",
        "Reflect",
        "Focus Energy",
        "Bide",
        "Metronome",
        "Mirror Move",
        "Self-Destruct",
        "Egg Bomb",
        "Lick",
        "Smog",
        "Sludge",
        "Bone Club",
        "Fire Blast",
        "Waterfall",
        "Clamp",
        "Swift",
        "Skull Bash",
        "Spike Cannon",
        "Constrict",
        "Amnesia",
        "Kinesis",
        "Soft-Boiled",
        "High Jump Kick",
        "Glare",
        "Dream Eater",
        "Poison Gas",
        "Barrage",
        "Leech Life",
        "Lovely Kiss",
        "Sky Attack",
        "Transform",
        "Bubble",
        "Dizzy Punch",
        "Spore",
        "Flash",
        "Psywave",
        "Splash",
        "Acid Armor",
        "Crabhammer",
        "Explosion",
        "Fury Swipes",
        "Bonemerang",
        "Rest",
        "Rock Slide",
        "Hyper Fang",
        "Sharpen",
        "Conversion",
        "Tri Attack",
        "Super Fang",
        "Slash",
        "Substitute",
        "Struggle",
        "Sketch",
        "Triple Kick",
        "Thief",
        "Spider Web",
        "Mind Reader",
        "Nightmare",
        "Flame Wheel",
        "Snore",
        "Curse",
        "Flail",
        "Conversion 2",
        "Aeroblast",
        "Cotton Spore",
        "Reversal",
        "Spite",
        "Powder Snow",
        "Protect",
        "Mach Punch",
        "Scary Face",
        "Feint Attack",
        "Sweet Kiss",
        "Belly Drum",
        "Sludge Bomb",
        "Mud-Slap",
        "Octazooka",
        "Spikes",
        "Zap Cannon",
        "Foresight",
        "Destiny Bond",
        "Perish Song",
        "Icy Wind",
        "Detect",
        "Bone Rush",
        "Lock-On",
        "Outrage",
        "Sandstorm",
        "Giga Drain",
        "Endure",
        "Charm",
        "Rollout",
        "False Swipe",
        "Swagger",
        "Milk Drink",
        "Spark",
        "Fury Cutter",
        "Steel Wing",
        "Mean Look",
        "Attract",
        "Sleep Talk",
        "Heal Bell",
        "Return",
        "Present",
        "Frustration",
        "Safeguard",
        "Pain Split",
        "Sacred Fire",
        "Magnitude",
        "Dynamic Punch",
        "Megahorn",
        "Dragon Breath",
        "Baton Pass",
        "Encore",
        "Pursuit",
        "Rapid Spin",
        "Sweet Scent",
        "Iron Tail",
        "Metal Claw",
        "Vital Throw",
        "Morning Sun",
        "Synthesis",
        "Moonlight",
        "Hidden Power",
        "Cross Chop",
        "Twister",
        "Rain Dance",
        "Sunny Day",
        "Crunch",
        "Mirror Coat",
        "Psych Up",
        "Extreme Speed",
        "Ancient Power",
        "Shadow Ball",
        "Future Sight",
        "Rock Smash",
        "Whirlpool",
        "Beat Up",
        "Fake Out",
        "Uproar",
        "Stockpile",
        "Spit Up",
        "Swallow",
        "Heat Wave",
        "Hail",
        "Torment",
        "Flatter",
        "Will-O-Wisp",
        "Memento",
        "Facade",
        "Focus Punch",
        "Smelling Salts",
        "Follow Me",
        "Nature Power",
        "Charge",
        "Taunt",
        "Helping Hand",
        "Trick",
        "Role Play",
        "Wish",
        "Assist",
        "Ingrain",
        "Superpower",
        "Magic Coat",
        "Recycle",
        "Revenge",
        "Brick Break",
        "Yawn",
        "Knock Off",
        "Endeavor",
        "Eruption",
        "Skill Swap",
        "Imprison",
        "Refresh",
        "Grudge",
        "Snatch",
        "Secret Power",
        "Dive",
        "Arm Thrust",
        "Camouflage",
        "Tail Glow",
        "Luster Purge",
        "Mist Ball",
        "Feather Dance",
        "Teeter Dance",
        "Blaze Kick",
        "Mud Sport",
        "Ice Ball",
        "Needle Arm",
        "Slack Off",
        "Hyper Voice",
        "Poison Fang",
        "Crush Claw",
        "Blast Burn",
        "Hydro Cannon",
        "Meteor Mash",
        "Astonish",
        "Weather Ball",
        "Aromatherapy",
        "Fake Tears",
        "Air Cutter",
        "Overheat",
        "Odor Sleuth",
        "Rock Tomb",
        "Silver Wind",
        "Metal Sound",
        "Grass Whistle",
        "Tickle",
        "Cosmic Power",
        "Water Spout",
        "Signal Beam",
        "Shadow Punch",
        "Extrasensory",
        "Sky Uppercut",
        "Sand Tomb",
        "Sheer Cold",
        "Muddy Water",
        "Bullet Seed",
        "Aerial Ace",
        "Icicle Spear",
        "Iron Defense",
        "Block",
        "Howl",
        "Dragon Claw",
        "Frenzy Plant",
        "Bulk Up",
        "Bounce",
        "Mud Shot",
        "Poison Tail",
        "Covet",
        "Volt Tackle",
        "Magical Leaf",
        "Water Sport",
        "Calm Mind",
        "Leaf Blade",
        "Dragon Dance",
        "Rock Blast",
        "Shock Wave",
        "Water Pulse",
        "Doom Desire",
        "Psycho Boost",
        "Roost",
        "Gravity",
        "Miracle Eye",
        "Wake-Up Slap",
        "Hammer Arm",
        "Gyro Ball",
        "Healing Wish",
        "Brine",
        "Natural Gift",
        "Feint",
        "Pluck",
        "Tailwind",
        "Acupressure",
        "Metal Burst",
        "U-turn",
        "Close Combat",
        "Payback",
        "Assurance",
        "Embargo",
        "Fling",
        "Psycho Shift",
        "Trump Card",
        "Heal Block",
        "Wring Out",
        "Power Trick",
        "Gastro Acid",
        "Lucky Chant",
        "Me First",
        "Copycat",
        "Power Swap",
        "Guard Swap",
        "Punishment",
        "Last Resort",
        "Worry Seed",
        "Sucker Punch",
        "Toxic Spikes",
        "Heart Swap",
        "Aqua Ring",
        "Magnet Rise",
        "Flare Blitz",
        "Force Palm",
        "Aura Sphere",
        "Rock Polish",
        "Poison Jab",
        "Dark Pulse",
        "Night Slash",
        "Aqua Tail",
        "Seed Bomb",
        "Air Slash",
        "X-Scissor",
        "Bug Buzz",
        "Dragon Pulse",
        "Dragon Rush",
        "Power Gem",
        "Drain Punch",
        "Vacuum Wave",
        "Focus Blast",
        "Energy Ball",
        "Brave Bird",
        "Earth Power",
        "Switcheroo",
        "Giga Impact",
        "Nasty Plot",
        "Bullet Punch",
        "Avalanche",
        "Ice Shard",
        "Shadow Claw",
        "Thunder Fang",
        "Ice Fang",
        "Fire Fang",
        "Shadow Sneak",
        "Mud Bomb",
        "Psycho Cut",
        "Zen Headbutt",
        "Mirror Shot",
        "Flash Cannon",
        "Rock Climb",
        "Defog",
        "Trick Room",
        "Draco Meteor",
        "Discharge",
        "Lava Plume",
        "Leaf Storm",
        "Power Whip",
        "Rock Wrecker",
        "Cross Poison",
        "Gunk Shot",
        "Iron Head",
        "Magnet Bomb",
        "Stone Edge",
        "Captivate",
        "Stealth Rock",
        "Grass Knot",
        "Chatter",
        "Judgment",
        "Bug Bite",
        "Charge Beam",
        "Wood Hammer",
        "Aqua Jet",
        "Attack Order",
        "Defend Order",
        "Heal Order",
        "Head Smash",
        "Double Hit",
        "Roar of Time",
        "Spacial Rend",
        "Lunar Dance",
        "Crush Grip",
        "Magma Storm",
        "Dark Void",
        "Seed Flare",
        "Ominous Wind",
        "Shadow Force",
        "Hone Claws",
        "Wide Guard",
        "Guard Split",
        "Power Split",
        "Wonder Room",
        "Psyshock",
        "Venoshock",
        "Autotomize",
        "Rage Powder",
        "Telekinesis",
        "Magic Room",
        "Smack Down",
        "Storm Throw",
        "Flame Burst",
        "Sludge Wave",
        "Quiver Dance",
        "Heavy Slam",
        "Synchronoise",
        "Electro Ball",
        "Soak",
        "Flame Charge",
        "Coil",
        "Low Sweep",
        "Acid Spray",
        "Foul Play",
        "Simple Beam",
        "Entrainment",
        "After You",
        "Round",
        "Echoed Voice",
        "Chip Away",
        "Clear Smog",
        "Stored Power",
        "Quick Guard",
        "Ally Switch",
        "Scald",
        "Shell Smash",
        "Heal Pulse",
        "Hex",
        "Sky Drop",
        "Shift Gear",
        "Circle Throw",
        "Incinerate",
        "Quash",
        "Acrobatics",
        "Reflect Type",
        "Retaliate",
        "Final Gambit",
        "Bestow",
        "Inferno",
        "Water Pledge",
        "Fire Pledge",
        "Grass Pledge",
        "Volt Switch",
        "Struggle Bug",
        "Bulldoze",
        "Frost Breath",
        "Dragon Tail",
        "Work Up",
        "Electroweb",
        "Wild Charge",
        "Drill Run",
        "Dual Chop",
        "Heart Stamp",
        "Horn Leech",
        "Sacred Sword",
        "Razor Shell",
        "Heat Crash",
        "Leaf Tornado",
        "Steamroller",
        "Cotton Guard",
        "Night Daze",
        "Psystrike",
        "Tail Slap",
        "Hurricane",
        "Head Charge",
        "Gear Grind",
        "Searing Shot",
        "Techno Blast",
        "Relic Song",
        "Secret Sword",
        "Glaciate",
        "Bolt Strike",
        "Blue Flare",
        "Fiery Dance",
        "Freeze Shock",
        "Ice Burn",
        "Snarl",
        "Icicle Crash",
        "V-create",
        "Fusion Flare",
        "Fusion Bolt",
        "Flying Press",
        "Mat Block",
        "Belch",
        "Rototiller",
        "Sticky Web",
        "Fell Stinger",
        "Phantom Force",
        "Trick-or-Treat",
        "Noble Roar",
        "Ion Deluge",
        "Parabolic Charge",
        "Forest's Curse",
        "Petal Blizzard",
        "Freeze-Dry",
        "Disarming Voice",
        "Parting Shot",
        "Topsy-Turvy",
        "Draining Kiss",
        "Crafty Shield",
        "Flower Shield",
        "Grassy Terrain",
        "Misty Terrain",
        "Electrify",
        "Play Rough",
        "Fairy Wind",
        "Moonblast",
        "Boomburst",
        "Fairy Lock",
        "King's Shield",
        "Play Nice",
        "Confide",
        "Diamond Storm",
        "Steam Eruption",
        "Hyperspace Hole",
        "Water Shuriken",
        "Mystical Fire",
        "Spiky Shield",
        "Aromatic Mist",
        "Eerie Impulse",
        "Venom Drench",
        "Powder",
        "Geomancy",
        "Magnetic Flux",
        "Happy Hour",
        "Electric Terrain",
        "Dazzling Gleam",
        "Celebrate",
        "Hold Hands",
        "Baby-Doll Eyes",
        "Nuzzle",
        "Hold Back",
        "Infestation",
        "Power-Up Punch",
        "Oblivion Wing",
        "Thousand Arrows",
        "Thousand Waves",
        "Land's Wrath",
        "Light of Ruin",
        "Origin Pulse",
        "Precipice Blades",
        "Dragon Ascent",
        "Hyperspace Fury",
        "Breakneck Blitz",
        "Breakneck Blitz",
        "All-Out Pummeling",
        "All-Out Pummeling",
        "Supersonic Skystrike",
        "Supersonic Skystrike",
        "Acid Downpour",
        "Acid Downpour",
        "Tectonic Rage",
        "Tectonic Rage",
        "Continental Crush",
        "Continental Crush",
        "Savage Spin-Out",
        "Savage Spin-Out",
        "Never-Ending Nightmare",
        "Never-Ending Nightmare",
        "Corkscrew Crash",
        "Corkscrew Crash",
        "Inferno Overdrive",
        "Inferno Overdrive",
        "Hydro Vortex",
        "Hydro Vortex",
        "Bloom Doom",
        "Bloom Doom",
        "Gigavolt Havoc",
        "Gigavolt Havoc",
        "Shattered Psyche",
        "Shattered Psyche",
        "Subzero Slammer",
        "Subzero Slammer",
        "Devastating Drake",
        "Devastating Drake",
        "Black Hole Eclipse",
        "Black Hole Eclipse",
        "Twinkle Tackle",
        "Twinkle Tackle",
        "Catastropika",
        "Shore Up",
        "First Impression",
        "Baneful Bunker",
        "Spirit Shackle",
        "Darkest Lariat",
        "Sparkling Aria",
        "Ice Hammer",
        "Floral Healing",
        "High Horsepower",
        "Strength Sap",
        "Solar Blade",
        "Leafage",
        "Spotlight",
        "Toxic Thread",
        "Laser Focus",
        "Gear Up",
        "Throat Chop",
        "Pollen Puff",
        "Anchor Shot",
        "Psychic Terrain",
        "Lunge",
        "Fire Lash",
        "Power Trip",
        "Burn Up",
        "Speed Swap",
        "Smart Strike",
        "Purify",
        "Revelation Dance",
        "Core Enforcer",
        "Trop Kick",
        "Instruct",
        "Beak Blast",
        "Clanging Scales",
        "Dragon Hammer",
        "Brutal Swing",
        "Aurora Veil",
        "Sinister Arrow Raid",
        "Malicious Moonsault",
        "Oceanic Operetta",
        "Guardian of Alola",
        "Soul-Stealing 7-Star Strike",
        "Stoked Sparksurfer",
        "Pulverizing Pancake",
        "Extreme Evoboost",
        "Genesis Supernova",
        "Shell Trap",
        "Fleur Cannon",
        "Psychic Fangs",
        "Stomping Tantrum",
        "Shadow Bone",
        "Accelerock",
        "Liquidation",
        "Prismatic Laser",
        "Spectral Thief",
        "Sunsteel Strike",
        "Moongeist Beam",
        "Tearful Look",
        "Zing Zap",
        "Nature's Madness",
        "Multi-Attack",
        "10,000,000 Volt Thunderbolt",
        "Mind Blown",
        "Plasma Fists",
        "Photon Geyser",
        "Light That Burns the Sky",
        "Searing Sunraze Smash",
        "Menacing Moonraze Maelstrom",
        "Let's Snuggle Forever",
        "Splintered Stormshards",
        "Clangorous Soulblaze",
        "Zippy Zap",
        "Splishy Splash",
        "Floaty Fall",
        "Pika Papow",
        "Bouncy Bubble",
        "Buzzy Buzz",
        "Sizzly Slide",
        "Glitzy Glow",
        "Baddy Bad",
        "Sappy Seed",
        "Freezy Frost",
        "Sparkly Swirl",
        "Veevee Volley",
        "Double Iron Bash"
    };

    extern int moveID;

    struct Moves {
        StringVector name;
        vector<int> choiceNo;
    };

    void SelectAMove(MenuEntry *entry);

    struct Origins {
        const char *name;
        int choiceNo;
        int generationFrom;
    };

    static const Origins allOrigins[30] = {
        {"Sun", 30, 7},
        {"Moon", 31, 7},
        {"Ultra Sun", 32, 7},
        {"Ultra Moon", 33, 7},
        {"X", 24, 6},
        {"Y", 25, 6},
        {"Omega Ruby", 27, 6},
        {"Alpha Sapphire", 26, 6},
        {"Black", 21, 5},
        {"White", 20, 5},
        {"Black 2", 23, 5},
        {"White 2", 22, 5},
        {"Diamond", 10, 4},
        {"Pearl", 11, 4},
        {"Platinum", 12, 4},
        {"HeatGold", 7, 4},
        {"SoulSilver", 8, 4},
        {"Ruby", 2, 3},
        {"Sapphire", 1, 3},
        {"Emerald", 3, 3},
        {"FireRed", 4, 2},
        {"LeafGreen", 5, 2},
        {"Colosseum/XD", 15, 3},
        {"Gold", 39, 2},
        {"Silver", 40, 2},
        {"Crystal", 41, 2},
        {"Red", 35, 1},
        {"Blue [INT]/Green [JP]", 36, 1},
        {"Blue [JP]", 37, 1},
        {"Yellow", 38, 1}
    };

    struct Locations {
        int choiceNo;
        const char *name;
    };

    static const Locations allLocs1[106] = {
        {2, "Mystery Zone"},
        {4, "Faraway Place"},
        {6, "Vaniville Town"},
        {8, "Route 1"},
        {9, "Vaniville Pathway"},
        {10, "Aquacorde Town"},
        {12, "Route 2"},
        {13, "Avance Trail"},
        {14, "Santalune Forest"},
        {16, "Route 3"},
        {17, "Ouvert Way"},
        {18, "Santalune City"},
        {20, "Route 4"},
        {21, "Parterre Way"},
        {22, "Lumiose City"},
        {24, "Prism Tower"},
        {26, "Lysandre Labs"},
        {28, "Route 5"},
        {29, "Versant Road"},
        {30, "Camphrier Town"},
        {32, "Shabboneau Castle"},
        {34, "Route 6"},
        {35, "Palais Lane"},
        {36, "Parfum Palace"},
        {38, "Route 7"},
        {39, "Rivière Walk"},
        {40, "Cyllage City"},
        {42, "Route 8"},
        {43, "Muraille Coast"},
        {44, "Ambrette Town"},
        {46, "Route 9"},
        {47, "Spikes Passage"},
        {48, "Battle Chateau"},
        {50, "Route 10"},
        {51, "Menhir Trail"},
        {52, "Geosenge Town"},
        {54, "Route 11"},
        {55, "Miroir Way"},
        {56, "Reflection Cave"},
        {58, "Shalour City"},
        {60, "Tower of Mastery"},
        {62, "Route 12"},
        {63, "Fourrage Road"},
        {64, "Coumarine City"},
        {66, "Route 13"},
        {67, "Lumiose Badlands"},
        {68, "Route 14"},
        {69, "Laverre Nature Trail"},
        {70, "Laverre City"},
        {72, "Poké Ball Factory"},
        {74, "Route 15"},
        {75, "Brun Way"},
        {76, "Dendemille Town"},
        {78, "Route 16"},
        {79, "Mélancolie Path"},
        {82, "Frost Cavern"},
        {84, "Route 17"},
        {85, "Mamoswine Road"},
        {86, "Anistar City"},
        {88, "Route 18"},
        {89, "Vallée Étroite Way"},
        {90, "Couriway Town"},
        {92, "Route 19"},
        {93, "Grande Vallée Way"},
        {94, "Snowbelle City"},
        {96, "Route 20"},
        {97, "Winding Woods"},
        {98, "Pokémon Village"},
        {100, "Route 21"},
        {101, "Dernière Way"},
        {102, "Route 22"},
        {103, "Détourner Way"},
        {104, "Victory Road"},
        {106, "Pokémon League"},
        {108, "Kiloude City"},
        {110, "Battle Maison"},
        {112, "Azure Bay"},
        {114, "Dendemille Gate"},
        {116, "Couriway Gate"},
        {118, "Ambrette Gate"},
        {120, "Lumiose Gate"},
        {122, "Shalour Gate"},
        {124, "Coumarine Gate"},
        {126, "Laverre Gate"},
        {128, "Anistar Gate"},
        {130, "Snowbelle Gate"},
        {132, "Glittering Cave"},
        {134, "Connecting Cave"},
        {135, "Zubat Roost"},
        {136, "Kalos Power Plant"},
        {138, "Team Flare Secret HQ"},
        {140, "Terminus Cave"},
        {142, "Lost Hotel"},
        {144, "Chamber of Emptiness"},
        {146, "Sea Spirit’s Den"},
        {148, "Friend Safari"},
        {150, "Blazing Chamber"},
        {152, "Flood Chamber"},
        {154, "Ironworks Chamber"},
        {156, "Dragonmark Chamber"},
        {158, "Radiant Chamber"},
        {160, "Pokémon League Gate"},
        {162, "Lumiose Station"},
        {164, "Kiloude Station"},
        {166, "Ambrette Aquarium"},
        {168, "Unknown Dungeon"}
    };

    static const Locations allLocs2[93] = {
        {170, "Littleroot Town"},
        {172, "Oldale Town"},
        {174, "Dewford Town"},
        {176, "Lavaridge Town"},
        {178, "Fallarbor Town"},
        {180, "Verdanturf Town"},
        {182, "Pacifidlog Town"},
        {184, "Petalburg City"},
        {186, "Slateport City"},
        {188, "Mauville City"},
        {190, "Rustboro City"},
        {192, "Fortree City"},
        {194, "Lilycove City"},
        {196, "Mossdeep City"},
        {198, "Sootopolis City"},
        {200, "Ever Grande City"},
        {202, "Pokémon League"},
        {204, "Route 101"},
        {206, "Route 102"},
        {208, "Route 103"},
        {210, "Route 104"},
        {212, "Route 105"},
        {214, "Route 106"},
        {216, "Route 107"},
        {218, "Route 108"},
        {220, "Route 109"},
        {222, "Route 110"},
        {224, "Route 111"},
        {226, "Route 112"},
        {228, "Route 113"},
        {230, "Route 114"},
        {232, "Route 115"},
        {234, "Route 116"},
        {236, "Route 117"},
        {238, "Route 118"},
        {240, "Route 119"},
        {242, "Route 120"},
        {244, "Route 121"},
        {246, "Route 122"},
        {248, "Route 123"},
        {250, "Route 124"},
        {252, "Route 125"},
        {254, "Route 126"},
        {256, "Route 127"},
        {258, "Route 128"},
        {260, "Route 129"},
        {262, "Route 130"},
        {264, "Route 131"},
        {266, "Route 132"},
        {268, "Route 133"},
        {270, "Route 134"},
        {272, "Meteor Falls"},
        {274, "Rusturf Tunnel"},
        {276, "???"},
        {278, "Desert Ruins"},
        {280, "Granite Cave"},
        {282, "Petalburg Woods"},
        {284, "Mt. Chimney"},
        {286, "Jagged Pass"},
        {288, "Fiery Path"},
        {290, "Mt. Pyre"},
        {292, "Team Aqua Hideout"},
        {294, "Seafloor Cavern"},
        {296, "Cave of Origin"},
        {298, "Victory Road"},
        {300, "Shoal Cave"},
        {302, "New Mauville"},
        {304, "Sea Mauville"},
        {306, "Island Cave"},
        {308, "Ancient Tomb"},
        {310, "Sealed Chamber"},
        {312, "Scorched Slab"},
        {314, "Team Magma Hideout"},
        {316, "Sky Pillar"},
        {318, "Battle Resort"},
        {320, "Southern Island"},
        {322, "S.S. Tidal"},
        {324, "Safari Zone"},
        {326, "Mirage Forest"},
        {328, "Mirage Cave"},
        {330, "Mirage Island"},
        {332, "Mirage Mountain"},
        {334, "Trackless Forest"},
        {336, "Pathless Plain"},
        {338, "Nameless Cavern"},
        {340, "Fabled Cave"},
        {342, "Gnarled Den"},
        {344, "Crescent Isle"},
        {346, "Secret Islet"},
        {348, "Soaring in the sky"},
        {350, "Secret Shore"},
        {352, "Secret Meadow"},
        {354, "Secret Base"}
    };

    struct Balls {
        int choiceNo;
        const char *name;
        int generationFrom;
    };

    static const Balls allBalls[26] = {
        {4, "Poké Ball", 3},
        {3, "Great Ball", 3},
        {2, "Ultra Ball", 3},
        {26, "Beast Ball", 7},
        {16, "Cherish Ball", 4},
        {7, "Dive Ball", 3},
        {25, "Dream Ball", 5},
        {13, "Dusk Ball", 4},
        {17, "Fast Ball", 4},
        {22, "Friend Ball", 4},
        {14, "Heal Ball", 4},
        {20, "Heavy Ball", 4},
        {18, "Level Ball", 4},
        {21, "Love Ball", 4},
        {19, "Lure Ball", 4},
        {11, "Luxury Ball", 3},
        {1, "Master Ball", 3},
        {23, "Moon Ball", 4},
        {8, "Nest Ball", 3},
        {6, "Net Ball", 3},
        {12, "Premier Ball", 3},
        {15, "Quick Ball", 4},
        {9, "Repeat Ball", 3},
        {5, "Safari Ball", 3},
        {24, "Sport Ball", 4},
        {10, "Timer Ball", 3}
    };

    static const StringVector rib0Ribbons = {
        {"Champion Kalos"},
        {"Champion G3"},
        {"Champion Sinnoh"},
        {"Best Friends"},
        {"Training"},
        {"Battler Skillful"},
        {"Battler Expert"},
        {"Effort"}
    };

    static const StringVector rib1Ribbons = {
        {"Alert"},
        {"Shock"},
        {"Downcast"},
        {"Careless"},
        {"Relax"},
        {"Snooze"},
        {"Smile"},
        {"Gorgeous"}
    };

    static const StringVector rib2Ribbons = {
        {"Royal"},
        {"Gorgeous Royal"},
        {"Artist"},
        {"Footprint"},
        {"Record"},
        {"Legend"},
        {"Country"},
        {"National"}
    };

    static const StringVector rib3Ribbons = {
        {"Earth"},
        {"World"},
        {"Classic"},
        {"Premier"},
        {"Event"},
        {"Birthday"},
        {"Special"},
        {"Souvenir"}
    };

    static const StringVector rib4Ribbons = {
        {"Wishing"},
        {"Champion Battle"},
        {"Champion Regional"},
        {"Champion National"},
        {"Champion World"},
        {"Has Contest Memory Ribbon"},
        {"Has Battle Memory Ribbon"},
        {"Champion G6 Hoenn"}
    };

    static const StringVector rib5Ribbons = {
        {"Contest Star"},
        {"Master Coolness"},
        {"Master Beauty"},
        {"Master Cuteness"},
        {"Master Cleverness"},
        {"Master Toughness"},
        {"Champion Alola"},
        {"Battle Royale"}
    };

    static const StringVector rib6Ribbons = {
        {"Battle Tree Great"},
        {"Battle Tree Master"}
    };
}

#endif